apiVersion : apps/v1
kind: Deployment
metadata:
  name: aks-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-nginx
  template:
    metadata:
      labels:
        app: aks-nginx 
    spec:
      containers:
        - name: aks-nginx
          image: hub.docker.com/repository/docker/k8sdockerpro/aks-nginx
          ports:
          - containerPort: 80
